# Generated by Django 3.2.9 on 2021-11-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logistic',
            old_name='battery',
            new_name='volume',
        ),
        migrations.RenameField(
            model_name='logistic',
            old_name='cpu',
            new_name='where_from',
        ),
        migrations.RenameField(
            model_name='logistic',
            old_name='prod',
            new_name='where_to',
        ),
        migrations.RemoveField(
            model_name='logistic',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='logistic',
            name='color',
        ),
        migrations.RemoveField(
            model_name='logistic',
            name='display',
        ),
        migrations.RemoveField(
            model_name='logistic',
            name='memory',
        ),
        migrations.RemoveField(
            model_name='logistic',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='logistic',
            name='user',
        ),
        migrations.RemoveField(
            model_name='logistic',
            name='vin',
        ),
        migrations.AddField(
            model_name='logistic',
            name='weight',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
