# Generated by Django 3.2.9 on 2021-11-16 08:36

from django.db import migrations, models
import django.db.models.aggregates


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0002_auto_20211116_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistic',
            name='field_name_sum',
            field=models.IntegerField(default=1, verbose_name=django.db.models.aggregates.Sum('volume')),
            preserve_default=False,
        ),
    ]
