# Generated by Django 3.2.9 on 2021-11-17 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0003_logistic_field_name_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistic',
            name='field_name_sum',
            field=models.IntegerField(verbose_name='<django.db.models.fields.IntegerField> + 2 '),
        ),
    ]
