# Generated by Django 3.2.9 on 2021-11-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0004_alter_logistic_field_name_sum'),
    ]

    operations = [
        migrations.CreateModel(
            name='HitCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visits', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='logistic',
            name='field_name_sum',
        ),
        migrations.AddField(
            model_name='logistic',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
