# Generated by Django 3.2.9 on 2021-11-19 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0005_auto_20211119_0937'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HitCount',
        ),
    ]
