# Generated by Django 3.2.9 on 2021-11-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0006_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='prosmotr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
