# Generated by Django 3.2.9 on 2021-11-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0007_auto_20211118_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistic',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='просмотры'),
        ),
    ]
