# Generated by Django 3.2.9 on 2021-11-18 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0008_logistic_views'),
    ]

    operations = [
        migrations.DeleteModel(
            name='prosmotr',
        ),
    ]
